### ISSUE TITLE
just to be sure: zabbix template current?

### ISSUE THREAD

**Issue by joergmschulz** [tiredofit/docker-traefik#5]
(((replacing my own traefik with yours because of the traefik integration)))

As I'm not receiving any data yet using the .xml in the zabbix template directory: is this the current file, or do you have a more recent one hanging around?

**Comment by tiredofit** [comment]
I don't have a recent one quite yet! It's been on the list for sometime and I haven't been able to port it over to support the newer versions.

**Comment by joergmschulz** [comment]
ok - thank you anyway. Basic monitoring works, so that's a luxury issue.

**Comment by tiredofit** [comment]
I'm  heading over to Africa for a few weeks towards the end of the month and going to use the time in Air - 36 hours over 3 flights to do some of this stuff - so hopefully we should get better metrics soon.
